# coding=utf-8
#================================================================
# Editor: PyCharm
# Time: 2020/10/12 8:49
# Author: Zhang Songhua
# Description: *
#================================================================


IGNORE_KEYS = [
    'model.10',
    'model.11',
    'model.12',
    'model.13',
    'model.14',
    'model.15',
    'model.16',
    'model.17',
    'model.18',
    'model.19',
    'model.20',
    'model.21',
    'model.22',
    'model.23',
    'model.24',
]

KEY_MAP = {
    "model.0.conv.conv.weight"              :"_Yolov5__backnone.focus.conv_f.conv.0.weight",
    "model.0.conv.bn.weight"                :"_Yolov5__backnone.focus.conv_f.conv.1.weight",
    "model.0.conv.bn.bias"                  :"_Yolov5__backnone.focus.conv_f.conv.1.bias",
    "model.0.conv.bn.running_mean"          :"_Yolov5__backnone.focus.conv_f.conv.1.running_mean",
    "model.0.conv.bn.running_var"           :"_Yolov5__backnone.focus.conv_f.conv.1.running_var",
#    "model.0.conv.bn.num_batches_tracked",

    "model.1.conv.weight"                   :"_Yolov5__backnone.conv1.conv.0.weight",
    "model.1.bn.weight"                     :"_Yolov5__backnone.conv1.conv.1.weight",
    "model.1.bn.bias"                       :"_Yolov5__backnone.conv1.conv.1.bias",
    "model.1.bn.running_mean"               :"_Yolov5__backnone.conv1.conv.1.running_mean",
    "model.1.bn.running_var"                :"_Yolov5__backnone.conv1.conv.1.running_var",
#    "model.1.bn.num_batches_tracked",

    "model.2.cv1.conv.weight"               :"_Yolov5__backnone.bottleneckCSP1.conv1.conv.0.weight",
    "model.2.cv1.bn.weight"                 :"_Yolov5__backnone.bottleneckCSP1.conv1.conv.1.weight",
    "model.2.cv1.bn.bias"                   :"_Yolov5__backnone.bottleneckCSP1.conv1.conv.1.bias",
    "model.2.cv1.bn.running_mean"           :"_Yolov5__backnone.bottleneckCSP1.conv1.conv.1.running_mean",
    "model.2.cv1.bn.running_var"            :"_Yolov5__backnone.bottleneckCSP1.conv1.conv.1.running_var",
#    "model.2.cv1.bn.num_batches_tracked",
    "model.2.cv2.weight"                    :"_Yolov5__backnone.bottleneckCSP1.conv3.weight",
    "model.2.cv3.weight"                    :"_Yolov5__backnone.bottleneckCSP1.conv2.weight",
    "model.2.cv4.conv.weight"               :"_Yolov5__backnone.bottleneckCSP1.conv4.conv.0.weight",
    "model.2.cv4.bn.weight"                 :"_Yolov5__backnone.bottleneckCSP1.conv4.conv.1.weight",
    "model.2.cv4.bn.bias"                   :"_Yolov5__backnone.bottleneckCSP1.conv4.conv.1.bias",
    "model.2.cv4.bn.running_mean"           :"_Yolov5__backnone.bottleneckCSP1.conv4.conv.1.running_mean",
    "model.2.cv4.bn.running_var"            :"_Yolov5__backnone.bottleneckCSP1.conv4.conv.1.running_var",
#    "model.2.cv4.bn.num_batches_tracked",
    "model.2.bn.weight"                     :"_Yolov5__backnone.bottleneckCSP1.bl.bl.0.weight",
    "model.2.bn.bias"                       :"_Yolov5__backnone.bottleneckCSP1.bl.bl.0.bias",
    "model.2.bn.running_mean"               :"_Yolov5__backnone.bottleneckCSP1.bl.bl.0.running_mean",
    "model.2.bn.running_var"                :"_Yolov5__backnone.bottleneckCSP1.bl.bl.0.running_var",
#    "model.2.bn.num_batches_tracked",
    "model.2.m.0.cv1.conv.weight"           :"_Yolov5__backnone.bottleneckCSP1.bottleneck.0.bottleneck.0.conv.0.weight",
    "model.2.m.0.cv1.bn.weight"             :"_Yolov5__backnone.bottleneckCSP1.bottleneck.0.bottleneck.0.conv.1.weight",
    "model.2.m.0.cv1.bn.bias"               :"_Yolov5__backnone.bottleneckCSP1.bottleneck.0.bottleneck.0.conv.1.bias",
    "model.2.m.0.cv1.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP1.bottleneck.0.bottleneck.0.conv.1.running_mean",
    "model.2.m.0.cv1.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP1.bottleneck.0.bottleneck.0.conv.1.running_var",
#    "model.2.m.0.cv1.bn.num_batches_tracked",
    "model.2.m.0.cv2.conv.weight"           :"_Yolov5__backnone.bottleneckCSP1.bottleneck.0.bottleneck.1.conv.0.weight",
    "model.2.m.0.cv2.bn.weight"             :"_Yolov5__backnone.bottleneckCSP1.bottleneck.0.bottleneck.1.conv.1.weight",
    "model.2.m.0.cv2.bn.bias"               :"_Yolov5__backnone.bottleneckCSP1.bottleneck.0.bottleneck.1.conv.1.bias",
    "model.2.m.0.cv2.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP1.bottleneck.0.bottleneck.1.conv.1.running_mean",
    "model.2.m.0.cv2.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP1.bottleneck.0.bottleneck.1.conv.1.running_var",
#    "model.2.m.0.cv2.bn.num_batches_tracked",

    "model.3.conv.weight"                   :"_Yolov5__backnone.conv2.conv.0.weight",
    "model.3.bn.weight"                     :"_Yolov5__backnone.conv2.conv.1.weight",
    "model.3.bn.bias"                       :"_Yolov5__backnone.conv2.conv.1.bias",
    "model.3.bn.running_mean"               :"_Yolov5__backnone.conv2.conv.1.running_mean",
    "model.3.bn.running_var"                :"_Yolov5__backnone.conv2.conv.1.running_var",
#    "model.3.bn.num_batches_tracked",

    "model.4.cv1.conv.weight"               :"_Yolov5__backnone.bottleneckCSP2.conv1.conv.0.weight",
    "model.4.cv1.bn.weight"                 :"_Yolov5__backnone.bottleneckCSP2.conv1.conv.1.weight",
    "model.4.cv1.bn.bias"                   :"_Yolov5__backnone.bottleneckCSP2.conv1.conv.1.bias",
    "model.4.cv1.bn.running_mean"           :"_Yolov5__backnone.bottleneckCSP2.conv1.conv.1.running_mean",
    "model.4.cv1.bn.running_var"            :"_Yolov5__backnone.bottleneckCSP2.conv1.conv.1.running_var",
#    "model.4.cv1.bn.num_batches_tracked",
    "model.4.cv2.weight"                    :"_Yolov5__backnone.bottleneckCSP2.conv3.weight",
    "model.4.cv3.weight"                    :"_Yolov5__backnone.bottleneckCSP2.conv2.weight",
    "model.4.cv4.conv.weight"               :"_Yolov5__backnone.bottleneckCSP2.conv4.conv.0.weight",
    "model.4.cv4.bn.weight"                 :"_Yolov5__backnone.bottleneckCSP2.conv4.conv.1.weight",
    "model.4.cv4.bn.bias"                   :"_Yolov5__backnone.bottleneckCSP2.conv4.conv.1.bias",
    "model.4.cv4.bn.running_mean"           :"_Yolov5__backnone.bottleneckCSP2.conv4.conv.1.running_mean",
    "model.4.cv4.bn.running_var"            :"_Yolov5__backnone.bottleneckCSP2.conv4.conv.1.running_var",
#    "model.4.cv4.bn.num_batches_tracked",
    "model.4.bn.weight"                     :"_Yolov5__backnone.bottleneckCSP2.bl.bl.0.weight",
    "model.4.bn.bias"                       :"_Yolov5__backnone.bottleneckCSP2.bl.bl.0.bias",
    "model.4.bn.running_mean"               :"_Yolov5__backnone.bottleneckCSP2.bl.bl.0.running_mean",
    "model.4.bn.running_var"                :"_Yolov5__backnone.bottleneckCSP2.bl.bl.0.running_var",
#    "model.4.bn.num_batches_tracked",
    "model.4.m.0.cv1.conv.weight"           :"_Yolov5__backnone.bottleneckCSP2.bottleneck.0.bottleneck.0.conv.0.weight",
    "model.4.m.0.cv1.bn.weight"             :"_Yolov5__backnone.bottleneckCSP2.bottleneck.0.bottleneck.0.conv.1.weight",
    "model.4.m.0.cv1.bn.bias"               :"_Yolov5__backnone.bottleneckCSP2.bottleneck.0.bottleneck.0.conv.1.bias",
    "model.4.m.0.cv1.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP2.bottleneck.0.bottleneck.0.conv.1.running_mean",
    "model.4.m.0.cv1.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP2.bottleneck.0.bottleneck.0.conv.1.running_var",
#    "model.4.m.0.cv1.bn.num_batches_tracked",
    "model.4.m.0.cv2.conv.weight"           :"_Yolov5__backnone.bottleneckCSP2.bottleneck.0.bottleneck.1.conv.0.weight",
    "model.4.m.0.cv2.bn.weight"             :"_Yolov5__backnone.bottleneckCSP2.bottleneck.0.bottleneck.1.conv.1.weight",
    "model.4.m.0.cv2.bn.bias"               :"_Yolov5__backnone.bottleneckCSP2.bottleneck.0.bottleneck.1.conv.1.bias",
    "model.4.m.0.cv2.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP2.bottleneck.0.bottleneck.1.conv.1.running_mean",
    "model.4.m.0.cv2.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP2.bottleneck.0.bottleneck.1.conv.1.running_var",
#    "model.4.m.0.cv2.bn.num_batches_tracked",
    "model.4.m.1.cv1.conv.weight"           :"_Yolov5__backnone.bottleneckCSP2.bottleneck.1.bottleneck.0.conv.0.weight",
    "model.4.m.1.cv1.bn.weight"             :"_Yolov5__backnone.bottleneckCSP2.bottleneck.1.bottleneck.0.conv.1.weight",
    "model.4.m.1.cv1.bn.bias"               :"_Yolov5__backnone.bottleneckCSP2.bottleneck.1.bottleneck.0.conv.1.bias",
    "model.4.m.1.cv1.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP2.bottleneck.1.bottleneck.0.conv.1.running_mean",
    "model.4.m.1.cv1.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP2.bottleneck.1.bottleneck.0.conv.1.running_var",
#    "model.4.m.1.cv1.bn.num_batches_tracked",
    "model.4.m.1.cv2.conv.weight"           :"_Yolov5__backnone.bottleneckCSP2.bottleneck.1.bottleneck.1.conv.0.weight",
    "model.4.m.1.cv2.bn.weight"             :"_Yolov5__backnone.bottleneckCSP2.bottleneck.1.bottleneck.1.conv.1.weight",
    "model.4.m.1.cv2.bn.bias"               :"_Yolov5__backnone.bottleneckCSP2.bottleneck.1.bottleneck.1.conv.1.bias",
    "model.4.m.1.cv2.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP2.bottleneck.1.bottleneck.1.conv.1.running_mean",
    "model.4.m.1.cv2.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP2.bottleneck.1.bottleneck.1.conv.1.running_var",
#    "model.4.m.1.cv2.bn.num_batches_tracked",
    "model.4.m.2.cv1.conv.weight"           :"_Yolov5__backnone.bottleneckCSP2.bottleneck.2.bottleneck.0.conv.0.weight",
    "model.4.m.2.cv1.bn.weight"             :"_Yolov5__backnone.bottleneckCSP2.bottleneck.2.bottleneck.0.conv.1.weight",
    "model.4.m.2.cv1.bn.bias"               :"_Yolov5__backnone.bottleneckCSP2.bottleneck.2.bottleneck.0.conv.1.bias",
    "model.4.m.2.cv1.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP2.bottleneck.2.bottleneck.0.conv.1.running_mean",
    "model.4.m.2.cv1.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP2.bottleneck.2.bottleneck.0.conv.1.running_var",
#    "model.4.m.2.cv1.bn.num_batches_tracked",
    "model.4.m.2.cv2.conv.weight"           :"_Yolov5__backnone.bottleneckCSP2.bottleneck.2.bottleneck.1.conv.0.weight",
    "model.4.m.2.cv2.bn.weight"             :"_Yolov5__backnone.bottleneckCSP2.bottleneck.2.bottleneck.1.conv.1.weight",
    "model.4.m.2.cv2.bn.bias"               :"_Yolov5__backnone.bottleneckCSP2.bottleneck.2.bottleneck.1.conv.1.bias",
    "model.4.m.2.cv2.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP2.bottleneck.2.bottleneck.1.conv.1.running_mean",
    "model.4.m.2.cv2.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP2.bottleneck.2.bottleneck.1.conv.1.running_var",
#    "model.4.m.2.cv2.bn.num_batches_tracked",

    "model.5.conv.weight"                   :"_Yolov5__backnone.conv3.conv.0.weight",
    "model.5.bn.weight"                     :"_Yolov5__backnone.conv3.conv.1.weight",
    "model.5.bn.bias"                       :"_Yolov5__backnone.conv3.conv.1.bias",
    "model.5.bn.running_mean"               :"_Yolov5__backnone.conv3.conv.1.running_mean",
    "model.5.bn.running_var"                :"_Yolov5__backnone.conv3.conv.1.running_var",
#    "model.5.bn.num_batches_tracked",

    "model.6.cv1.conv.weight"               :"_Yolov5__backnone.bottleneckCSP3.conv1.conv.0.weight",
    "model.6.cv1.bn.weight"                 :"_Yolov5__backnone.bottleneckCSP3.conv1.conv.1.weight",
    "model.6.cv1.bn.bias"                   :"_Yolov5__backnone.bottleneckCSP3.conv1.conv.1.bias",
    "model.6.cv1.bn.running_mean"           :"_Yolov5__backnone.bottleneckCSP3.conv1.conv.1.running_mean",
    "model.6.cv1.bn.running_var"            :"_Yolov5__backnone.bottleneckCSP3.conv1.conv.1.running_var",
#    "model.6.cv1.bn.num_batches_tracked",
    "model.6.cv2.weight"                    :"_Yolov5__backnone.bottleneckCSP3.conv3.weight",
    "model.6.cv3.weight"                    :"_Yolov5__backnone.bottleneckCSP3.conv2.weight",
    "model.6.cv4.conv.weight"               :"_Yolov5__backnone.bottleneckCSP3.conv4.conv.0.weight",
    "model.6.cv4.bn.weight"                 :"_Yolov5__backnone.bottleneckCSP3.conv4.conv.1.weight",
    "model.6.cv4.bn.bias"                   :"_Yolov5__backnone.bottleneckCSP3.conv4.conv.1.bias",
    "model.6.cv4.bn.running_mean"           :"_Yolov5__backnone.bottleneckCSP3.conv4.conv.1.running_mean",
    "model.6.cv4.bn.running_var"            :"_Yolov5__backnone.bottleneckCSP3.conv4.conv.1.running_var",
#    "model.6.cv4.bn.num_batches_tracked",
    "model.6.bn.weight"                     :"_Yolov5__backnone.bottleneckCSP3.bl.bl.0.weight",
    "model.6.bn.bias"                       :"_Yolov5__backnone.bottleneckCSP3.bl.bl.0.bias",
    "model.6.bn.running_mean"               :"_Yolov5__backnone.bottleneckCSP3.bl.bl.0.running_mean",
    "model.6.bn.running_var"                :"_Yolov5__backnone.bottleneckCSP3.bl.bl.0.running_var",
#    "model.6.bn.num_batches_tracked",
    "model.6.m.0.cv1.conv.weight"           :"_Yolov5__backnone.bottleneckCSP3.bottleneck.0.bottleneck.0.conv.0.weight",
    "model.6.m.0.cv1.bn.weight"             :"_Yolov5__backnone.bottleneckCSP3.bottleneck.0.bottleneck.0.conv.1.weight",
    "model.6.m.0.cv1.bn.bias"               :"_Yolov5__backnone.bottleneckCSP3.bottleneck.0.bottleneck.0.conv.1.bias",
    "model.6.m.0.cv1.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP3.bottleneck.0.bottleneck.0.conv.1.running_mean",
    "model.6.m.0.cv1.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP3.bottleneck.0.bottleneck.0.conv.1.running_var",
#    "model.6.m.0.cv1.bn.num_batches_tracked",
    "model.6.m.0.cv2.conv.weight"           :"_Yolov5__backnone.bottleneckCSP3.bottleneck.0.bottleneck.1.conv.0.weight",
    "model.6.m.0.cv2.bn.weight"             :"_Yolov5__backnone.bottleneckCSP3.bottleneck.0.bottleneck.1.conv.1.weight",
    "model.6.m.0.cv2.bn.bias"               :"_Yolov5__backnone.bottleneckCSP3.bottleneck.0.bottleneck.1.conv.1.bias",
    "model.6.m.0.cv2.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP3.bottleneck.0.bottleneck.1.conv.1.running_mean",
    "model.6.m.0.cv2.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP3.bottleneck.0.bottleneck.1.conv.1.running_var",
#    "model.6.m.0.cv2.bn.num_batches_tracked",
    "model.6.m.1.cv1.conv.weight"           :"_Yolov5__backnone.bottleneckCSP3.bottleneck.1.bottleneck.0.conv.0.weight",
    "model.6.m.1.cv1.bn.weight"             :"_Yolov5__backnone.bottleneckCSP3.bottleneck.1.bottleneck.0.conv.1.weight",
    "model.6.m.1.cv1.bn.bias"               :"_Yolov5__backnone.bottleneckCSP3.bottleneck.1.bottleneck.0.conv.1.bias",
    "model.6.m.1.cv1.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP3.bottleneck.1.bottleneck.0.conv.1.running_mean",
    "model.6.m.1.cv1.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP3.bottleneck.1.bottleneck.0.conv.1.running_var",
#    "model.6.m.1.cv1.bn.num_batches_tracked",
    "model.6.m.1.cv2.conv.weight"           :"_Yolov5__backnone.bottleneckCSP3.bottleneck.1.bottleneck.1.conv.0.weight",
    "model.6.m.1.cv2.bn.weight"             :"_Yolov5__backnone.bottleneckCSP3.bottleneck.1.bottleneck.1.conv.1.weight",
    "model.6.m.1.cv2.bn.bias"               :"_Yolov5__backnone.bottleneckCSP3.bottleneck.1.bottleneck.1.conv.1.bias",
    "model.6.m.1.cv2.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP3.bottleneck.1.bottleneck.1.conv.1.running_mean",
    "model.6.m.1.cv2.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP3.bottleneck.1.bottleneck.1.conv.1.running_var",
#    "model.6.m.1.cv2.bn.num_batches_tracked",
    "model.6.m.2.cv1.conv.weight"           :"_Yolov5__backnone.bottleneckCSP3.bottleneck.2.bottleneck.0.conv.0.weight",
    "model.6.m.2.cv1.bn.weight"             :"_Yolov5__backnone.bottleneckCSP3.bottleneck.2.bottleneck.0.conv.1.weight",
    "model.6.m.2.cv1.bn.bias"               :"_Yolov5__backnone.bottleneckCSP3.bottleneck.2.bottleneck.0.conv.1.bias",
    "model.6.m.2.cv1.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP3.bottleneck.2.bottleneck.0.conv.1.running_mean",
    "model.6.m.2.cv1.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP3.bottleneck.2.bottleneck.0.conv.1.running_var",
#    "model.6.m.2.cv1.bn.num_batches_tracked",
    "model.6.m.2.cv2.conv.weight"           :"_Yolov5__backnone.bottleneckCSP3.bottleneck.2.bottleneck.1.conv.0.weight",
    "model.6.m.2.cv2.bn.weight"             :"_Yolov5__backnone.bottleneckCSP3.bottleneck.2.bottleneck.1.conv.1.weight",
    "model.6.m.2.cv2.bn.bias"               :"_Yolov5__backnone.bottleneckCSP3.bottleneck.2.bottleneck.1.conv.1.bias",
    "model.6.m.2.cv2.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP3.bottleneck.2.bottleneck.1.conv.1.running_mean",
    "model.6.m.2.cv2.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP3.bottleneck.2.bottleneck.1.conv.1.running_var",
#   "model.6.m.2.cv2.bn.num_batches_tracked",

    "model.7.conv.weight"                   :"_Yolov5__backnone.conv4.conv.0.weight",
    "model.7.bn.weight"                     :"_Yolov5__backnone.conv4.conv.1.weight",
    "model.7.bn.bias"                       :"_Yolov5__backnone.conv4.conv.1.bias",
    "model.7.bn.running_mean"               :"_Yolov5__backnone.conv4.conv.1.running_mean",
    "model.7.bn.running_var"                :"_Yolov5__backnone.conv4.conv.1.running_var",
#    "model.7.bn.num_batches_tracked",

    "model.8.cv1.conv.weight"               :"_Yolov5__backnone.spp.conv1.conv.0.weight",
    "model.8.cv1.bn.weight"                 :"_Yolov5__backnone.spp.conv1.conv.1.weight",
    "model.8.cv1.bn.bias"                   :"_Yolov5__backnone.spp.conv1.conv.1.bias",
    "model.8.cv1.bn.running_mean"           :"_Yolov5__backnone.spp.conv1.conv.1.running_mean",
    "model.8.cv1.bn.running_var"            :"_Yolov5__backnone.spp.conv1.conv.1.running_var",
#   "model.8.cv1.bn.num_batches_tracked",
    "model.8.cv2.conv.weight"               :"_Yolov5__backnone.spp.conv2.conv.0.weight",
    "model.8.cv2.bn.weight"                 :"_Yolov5__backnone.spp.conv2.conv.1.weight",
    "model.8.cv2.bn.bias"                   :"_Yolov5__backnone.spp.conv2.conv.1.bias",
    "model.8.cv2.bn.running_mean"           :"_Yolov5__backnone.spp.conv2.conv.1.running_mean",
    "model.8.cv2.bn.running_var"            :"_Yolov5__backnone.spp.conv2.conv.1.running_var",
#    "model.8.cv2.bn.num_batches_tracked",

    "model.9.cv1.conv.weight"               :"_Yolov5__backnone.bottleneckCSP4.conv1.conv.0.weight",
    "model.9.cv1.bn.weight"                 :"_Yolov5__backnone.bottleneckCSP4.conv1.conv.1.weight",
    "model.9.cv1.bn.bias"                   :"_Yolov5__backnone.bottleneckCSP4.conv1.conv.1.bias",
    "model.9.cv1.bn.running_mean"           :"_Yolov5__backnone.bottleneckCSP4.conv1.conv.1.running_mean",
    "model.9.cv1.bn.running_var"            :"_Yolov5__backnone.bottleneckCSP4.conv1.conv.1.running_var",
#    "model.9.cv1.bn.num_batches_tracked",
    "model.9.cv2.weight"                    :"_Yolov5__backnone.bottleneckCSP4.conv3.weight",
    "model.9.cv3.weight"                    :"_Yolov5__backnone.bottleneckCSP4.conv2.weight",
    "model.9.cv4.conv.weight"               :"_Yolov5__backnone.bottleneckCSP4.conv4.conv.0.weight",
    "model.9.cv4.bn.weight"                 :"_Yolov5__backnone.bottleneckCSP4.conv4.conv.1.weight",
    "model.9.cv4.bn.bias"                   :"_Yolov5__backnone.bottleneckCSP4.conv4.conv.1.bias",
    "model.9.cv4.bn.running_mean"           :"_Yolov5__backnone.bottleneckCSP4.conv4.conv.1.running_mean",
    "model.9.cv4.bn.running_var"            :"_Yolov5__backnone.bottleneckCSP4.conv4.conv.1.running_var",
#    "model.9.cv4.bn.num_batches_tracked",
    "model.9.bn.weight"                     :"_Yolov5__backnone.bottleneckCSP4.bl.bl.0.weight",
    "model.9.bn.bias"                       :"_Yolov5__backnone.bottleneckCSP4.bl.bl.0.bias",
    "model.9.bn.running_mean"               :"_Yolov5__backnone.bottleneckCSP4.bl.bl.0.running_mean",
    "model.9.bn.running_var"                :"_Yolov5__backnone.bottleneckCSP4.bl.bl.0.running_var",
#    "model.9.bn.num_batches_tracked",
    "model.9.m.0.cv1.conv.weight"           :"_Yolov5__backnone.bottleneckCSP4.bottleneck.0.bottleneck.0.conv.0.weight",
    "model.9.m.0.cv1.bn.weight"             :"_Yolov5__backnone.bottleneckCSP4.bottleneck.0.bottleneck.0.conv.1.weight",
    "model.9.m.0.cv1.bn.bias"               :"_Yolov5__backnone.bottleneckCSP4.bottleneck.0.bottleneck.0.conv.1.bias",
    "model.9.m.0.cv1.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP4.bottleneck.0.bottleneck.0.conv.1.running_mean",
    "model.9.m.0.cv1.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP4.bottleneck.0.bottleneck.0.conv.1.running_var",
#    "model.9.m.0.cv1.bn.num_batches_tracked",
    "model.9.m.0.cv2.conv.weight"           :"_Yolov5__backnone.bottleneckCSP4.bottleneck.0.bottleneck.1.conv.0.weight",
    "model.9.m.0.cv2.bn.weight"             :"_Yolov5__backnone.bottleneckCSP4.bottleneck.0.bottleneck.1.conv.1.weight",
    "model.9.m.0.cv2.bn.bias"               :"_Yolov5__backnone.bottleneckCSP4.bottleneck.0.bottleneck.1.conv.1.bias",
    "model.9.m.0.cv2.bn.running_mean"       :"_Yolov5__backnone.bottleneckCSP4.bottleneck.0.bottleneck.1.conv.1.running_mean",
    "model.9.m.0.cv2.bn.running_var"        :"_Yolov5__backnone.bottleneckCSP4.bottleneck.0.bottleneck.1.conv.1.running_var",
#    "model.9.m.0.cv2.bn.num_batches_tracked",
}